In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])

In [3]:
ab

[6, 14, 24, 36, 50]

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a*b

array([ 6, 14, 24, 36, 50])

In [5]:
# Creating numpy array 
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
# Creating an array from scratch
np.zeros(10 , dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Creating random array
np.random.randint(0,10, size = 10)

array([9, 0, 3, 4, 8, 6, 2, 8, 4, 8])

In [8]:
# Creating a normally distributed array
np.random.normal(10,4, size = (3,4))

array([[ 8.85397946,  6.64518994, 14.60643109,  2.12609187],
       [13.25385302, 13.83296396, 15.18992353,  9.14651696],
       [ 6.39348642, 13.48118414,  7.12729073, 15.74880731]])

In [9]:
#-Features
a = np.random.randint(10, size = 5)

In [10]:
a.ndim

1

In [11]:
a.shape

(5,)

In [12]:
a.size

5

In [13]:
# Reshape
a = np.random.randint(1, 9, size = 9)
a.reshape(3,3)

array([[1, 2, 8],
       [5, 8, 1],
       [8, 7, 2]])

In [14]:
# Indexing
a = np.random.randint(10, size = 10)
a[0]

5

In [15]:
a[0:3]

array([5, 8, 4])

In [16]:
a[0] = 999

In [17]:
a

array([999,   8,   4,   3,   6,   0,   0,   5,   4,   8])

In [18]:
b = np.random.randint(10, size = (3,5))

In [19]:
b[0,0]

5

In [20]:
b[1, 1]

5

In [21]:
b[0, :]

array([5, 2, 4, 3, 2])

In [22]:
b[: , 0]

array([5, 8, 7])

In [23]:
b[0:2, 0:3]

array([[5, 2, 4],
       [8, 5, 7]])

In [24]:
# Fancy indexing
v = np.arange(0,30,3)
v[1]
catch = [1, 2, 3]
v[catch]

array([3, 6, 9])

In [25]:
# Conditional indexing
v = np.array([1,2,3,4,5])

In [26]:
v[v<3]

array([1, 2])

In [27]:
v[v !=3]

array([1, 2, 4, 5])

In [28]:
# Mathematical operations
c = np.array([1,2,3,4,5])

In [29]:
c/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
c* 5 /10

array([0.5, 1. , 1.5, 2. , 2.5])

In [31]:
c**2

array([ 1,  4,  9, 16, 25])

In [32]:
np.subtract(c,1)

array([0, 1, 2, 3, 4])

In [33]:
np.add(c,1)

array([2, 3, 4, 5, 6])

In [34]:
np.multiply(c,2)

array([ 2,  4,  6,  8, 10])

In [35]:
np.mean(c)

3.0

In [36]:
np.max(c)

5

In [37]:
np.var(c)

2.0

In [38]:
# Solving equations with two unknowns

# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5,1], [1,3]])
b = np.array([12,10])

np.linalg.solve(a,b)

array([1.85714286, 2.71428571])